config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :users
  resources :businesses do
    resources :reviews
  end
  get 'users/:user_id/profile', to: 'home#get_user_profile'
  put 'users/:user_id/profile/upload_photo', to: 'home#upload_photo'
  get 'business/search', to: 'businesses#search'
  get 'business/search_results', to: 'businesses#search_results'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
# frozen_string_literal: true

# Business controller
class BusinessesController < ApplicationController
  include BusinessesControllerConcern
  before_action :authenticate_user!, only: %i[create new destroy
                                              show edit update]
  def index
    @businesses = Business.all
  end

  def new
    @business = Business.new
  end

  def edit
    id = params[:id]
    @business = get_business(id)
    render 'businesses/edit'
  end

  def update
    id = params[:id]
    @business = get_business(id)
    if @business.user_id == current_user.id
      if @business.update(business_params)
        flash[:notice] = 'Business updated successfully'
        redirect_to businesses_path
      else
        flash[:error] = 'Update failed please try again'
      end
    else
      flash[:error] = 'You do not have authorization to perform this action'
    end
  end

  def search
    @locations = Business.all.map(&:business_location)
    render 'businesses/search'
  end

  def search_results
    business_name = params[:q]
    category = params[:category].present? ? params[:category] : nil
    location = params[:location].present? ? params[:location] : nil
    results = search_for_business(business_name, location, category)
    render json: results
  end

  def show
    @business = get_business(params[:id])
    @reviews = @business.reviews.order(created_at: :desc) if @business
    flash[:error] = 'Business not found' unless @business
    redirect_to businesses_path unless @business
  end

  def create
    business = Business.new(business_params)
    business[:user_id] = current_user.id
    if business.save
      flash[:notice] = 'Business registered successfully'
      redirect_to businesses_path
    else
      flash[:error] = business.errors.full_messages.first
      redirect_to new_business_path
    end
  end

  def destroy
    business = Business.find_by(id: params[:id])
    if business
      if business.user_id == current_user.id
        business.destroy
        flash[:notice] = 'Business deleted successfully'
        redirect_to businesses_path
      else
        flash[:error] = 'You do not have authorization to perform this action'
      end
    else
      flash[:error] = 'Business  not found'
    end
  end

  def business_params
    params.require(:business).permit(:business_name, :business_email,
                                     :business_location, :contact_number,
                                     :business_description, :category_id)
  end

  def get_business(id)
    Business.find_by(id: id)
  end
end

app/helpers/businesses_helper.rb
# frozen_string_literal: true

module BusinessesHelper
  def business_owner(current_user, business_owner_id)
    current_user == business_owner_id
  end
end

app/views/businesses/_business_cards.html.erb
<% unless @businesses.length == 0 %>
  <% @businesses.each do |business| %>
    <div class="col-xs-6 col-md-4">
      <div class="business-card">
        <div class="card border-light mb-3 card-min-height">
        <div class="card-header" style="font-size: 30px"><strong><%= business.business_name %></strong>
          <div class="social-media">
            <span><a href="http://www.facebook.com"><i class="fab fa-facebook-square"></i></a></span>
            <span><a href="http://"><i class="fab fa-twitter-square"></i></a></span>
            <span><a href="#"><i class="fab fa-youtube-square"></i></a></span>
            <span><a href="#"><i class="fab fa-linkedin"></i></a></span>
            <span><a href="#"><i class="fab fa-instagram"></i></a></span>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= business.category.name %></h5>
          <div class="business-card-text"><p class="card-text"><%= business.business_description %></p></div>
        </div>
        <a href="businesses/<%= business.id %>" class="btn btn-lg btn-info"> View Profile</a>
       </div>
      </div>
    </div>
  <% end %>
  <% else %>
  <div style="margin: 5rem auto">
    <div class="card text-white bg-dark mb-3">
      <div class="card-header">Ooops :)</div>
      <div class="card-body">
        <p class="card-text">No businesses registered yet</p>
      </div>
    </div>
  </div>
<% end %>

app/views/businesses/_delete_business.html.erb
<div class="modal fade" id="deleteBusinessModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete Business</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete business with name <%= @business.business_name %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        <button type="button" id="<%= @business.id %>" class="btn btn-danger confirmDeleteBusiness" data-dismiss="modal">Delete</button>
      </div>

    </div>
  </div>
</div>

app/views/businesses/edit.html.erb
<div class="d-flex justify-content-center">
  <div class="col-md-8">
    <h3 class="business-heading">Business Registration Form</h3>
    <%= render 'layouts/messages' %>
    <%= flash_toastr %>
    <%= form_for( :business, url: business_path(@business), method: :put ) do |f| %>
      <div class="form-group">
        <%= f.label :business_name, "Business Name" %><br>
        <%= f.text_field :business_name, :class => "form-control business-inputs" %>
      </div>
      <div class="form-group">
        <%= f.label :business_email, "Business Email" %><br>
        <%= f.email_field :business_email , {class: "form-control business-inputs"} %>
      </div>
      <div class="form-group">
        <%= f.label :business_location, "Business Location" %><br>
        <%= f.text_field :business_location , {class: "form-control business-inputs"} %>
      </div>
      <div class="form-group">
        <%= f.label :category_id, "Business Category" %><br>
        <% categories_array = Category.all.map { |category| [category.name, category.id] } %>
        <%= f.select :category_id, options_for_select(categories_array),{}, {class: "form-control business-inputs"} %>
      </div>
      <div class="form-group">
        <%= f.label :contact_number, "Contact Number"%><br>
        <%= f.text_field :contact_number , {class: "form-control business-inputs"} %>
      </div>
      <div class="form-group">
        <%= f.label :business_description, "Business Description" %><br>
        <%= f.text_area :business_description , {class: "form-control business-inputs"} %>
      </div>
      <div class="form-group">
        <%= f.submit("Update Business",{:class => "form-control business-inputs btn btn-info"})  %>
      </div>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/businesses/index.html.erb
<div class="businesses-background">
<div class="container">
  <%= render 'layouts/messages' %>
  <%= flash_toastr %>
  <div class="row">
      <%= render 'business_cards' %>
  </div>
</div>
</div>

app/views/businesses/new.html.erb
<div class="business-container text-light">
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="col-md-8">
      <h3 class="business-heading">Business Registration Form</h3>
        <%= render 'layouts/messages' %>
      <%= flash_toastr %>
          <%= form_for( :business, url: businesses_path ) do |f| %>
          <div class="form-group">
              <%= f.label :business_name, "Business Name" %><br>
              <%= f.text_field :business_name, :class => "form-control business-inputs" %>
            </div>
            <div class="form-group">
              <%= f.label :business_email, "Business Email" %><br>
              <%= f.email_field :business_email , {class: "form-control business-inputs"} %>
            </div>
            <div class="form-group">
              <%= f.label :business_location, "Business Location" %><br>
              <%= f.text_field :business_location , {class: "form-control business-inputs"} %>
            </div>
            <div class="form-group">
              <%= f.label :category_id, "Business Category" %><br>
              <% categories_array = Category.all.map { |category| [category.name, category.id] } %>
              <%= f.select :category_id, options_for_select(categories_array),{}, {class: "form-control business-inputs"} %>
            </div>
            <div class="form-group">
              <%= f.label :contact_number, "Contact Number"%><br>
              <%= f.text_field :contact_number , {class: "form-control business-inputs"} %>
            </div>
            <div class="form-group">
              <%= f.label :business_description, "Business Description" %><br>
              <%= f.text_area :business_description , {class: "form-control business-inputs"} %>
            </div>
            <div class="form-group">
              <%= f.submit({:class => "form-control business-inputs btn btn-info"})  %>
            </div>
          <% end %>
          </div>
        </div>
      </div>
  </div>

app/views/businesses/search.html.erb
<div class="container">
  <div class="we-connect-logo"></div>
  <form>
    <nav class="navbar navbar-expand-md navbar-light bg-dark">
      <a class="text-light navbar-brand" href="/business/search"><%= image_tag('logo.png', size: '45x42', alt: 'We Connect!') %>
        Search Businesses
      </a>
      <button type="button" class="navbar-toggler">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse">
        <ul class="ml-auto navbar-nav">
          <li class="nav-item-name-properties nav-item">
            <input name="businessName" placeholder="Start typing Business name.." class="business-name-input" type="text" id="business_name_search">
          </li>
          <li class="nav-item-name-properties nav-item">
            <label class="business-search-label">Filter By:</label>
          </li>
          <li class="nav-item-name-properties nav-item">
            <select class="form-control category-input">
              <option selected="true" disabled >Select a category..</option>
              <% Category.all.map do |category| %>
              <option value="<%= category.id %>"><%= category.name %></option>
              <% end %>
            </select>
            <%# categories_array = Category.all.map { |category| [category.name, category.id] } %>
            <%#= select_tag "Category", options_for_select(categories_array), class: "form-control category-input" %>
          </li>
          <li class="nav-item-name-properties nav-item">
            <select class="form-control location-input">
              <option selected disabled>Select location ..</option>
              <% @locations.each do |location| %>
                <option value="<%= location %>"><%= location %></option>
              <% end %>

            </select>
          </li>
        </ul>
      </div>
    </nav>
  </form>
  <div class="search-results">
    <h4 id="total-results" class="font-italic text-light"></h4>
    <span id="business-links"></span>
  </div>
</div>

app/views/businesses/show.html.erb
<div class="background-profile-image"><div class="container text-light">
<div class="row">
  <div class="bg-secondary col-6">
  <div class="content-left">
    <div class="form-group">
      <h1 id="profile-heading">Business Profile </h1>
      <%= render 'layouts/messages' %>
      <%= flash_toastr %>
      <div>
        <%# if business_owner(current_user.id, @business.user_id) %>

        <%=
          link_to options={controller: "businesses", action: "edit", id: @business.id}, html_options={class: "btn btn-info"} do
        %>
          <i class="fas fa-edit"></i>
        <% end %>
        <button type="button" data-toggle="modal" data-target="#deleteBusinessModal" class="btn-danger btn btn-secondary" style="margin-left: 5px;"><i class="fas fa-trash-alt"></i></button>
          <%# end %>
      </div>
    </div>
    <div class="form-group"><b>
      <label id="businessName">Business Name:</label></b>
      <br>
      <label class="profile-labels"><%= @business.business_name %></label>
    </div>
    <div class="form-group">
      <b><label id="businessLocation">Business Location:</label></b><br>
      <label class="profile-labels"><%= @business.business_location %></label>
    </div>
    <div class="form-group">
      <b><label id="businessEmail">Business Email:</label></b><br>
      <label class="profile-labels"><%= @business.business_email %></label>
    </div>
    <div class="form-group">
      <b><label>Contact Number:</label></b><br>
      <label class="profile-labels"><%= @business.contact_number %></label>
    </div>
    <div class="form-group">
      <b><label>Business Description:</label></b><br>
      <label class="profile-labels"> <%= @business.business_description %></label>
    </div>
    <div class="form-group">
      <b><label class="">Business Category:</label></b><br>
      <label class="profile-labels"><%= @business.category.name %></label>
    </div>
    </div>
    </div>
    <div class="bg-secondary col-6">
    <div class="container">
      <div class="content-right">
        <%# unless business_owner(current_user.id, @business.user_id) %>
        <%= form_for( :review, url: business_reviews_path(@business.id) ) do |f| %>
          <div class="form-group">
            <h3>Add Business Review:</h3>
            <div class="form-group">
              <%= f.label :title, "Title:" %><br>
              <%= f.text_field :title, :class => "form-control business-inputs" %>
            </div>
            <%= tinymce %>
            <%= f.text_area :body, :class => "tinymce"%>
            <div class="form-group">
              <%= f.submit("Add Review",{:class => "form-control business-inputs btn btn-info"})  %>
            </div>
          </div>
          <% end %>
          <%# end %>
      </div>
    </div>
  </div>
  <p>
    <a class="btn btn-info review-btn" data-toggle="collapse" href="#collapseReviews" role="button" aria-expanded="false">
      Show Reviews
    </a>
  </p>
  <div class="collapse review-card" id="collapseReviews">
  <div class="card text-center text-dark ">
    <div class="card-header">
      <%= @business.business_name %> Reviews
    </div>
    <% if @reviews.length > 0 %>
    <% @reviews.each do |review| %>
    <div class="card-body">
      <h5 class="card-title"><%= review.title %></h5>
      <p class="card-text"><%= raw review.body %></p>
    </div>
    <div class="card-footer text-muted">Posted on: <%= review.created_at.strftime("%b %d, %Y, %H : %M %p") %> </div><br>
    <% end %>
      <% else %>
      <div class="card-body">
        <h5 class="card-title">No reviews posted yet</h5>
    <% end %>
  </div>
  </div>
  </div>
</div>
  </div>
</div>
<%= render 'businesses/delete_business'%>