config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :users
  resources :businesses do
    resources :reviews
  end
  get 'users/:user_id/profile', to: 'home#get_user_profile'
  put 'users/:user_id/profile/upload_photo', to: 'home#upload_photo'
  get 'business/search', to: 'businesses#search'
  get 'business/search_results', to: 'businesses#search_results'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<% devise_error_messages! %>
<% flash.each do |key, value| %>
  <% if value.respond_to?('each')%>
    <% value.each do |message| %>
      <div class="alert alert-<%= get_flash_key(key) %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <%= message %>
      </div>
    <% end %>
    <% else %>
      <div class="alert alert-<%= get_flash_key(key) %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
  </div>
    <% end %>
<% end %>

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= image_tag('logo.png', size: '45x42') %>
  <%= link_to "WeConnect!", root_path, class: "navbar-brand"  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
       <a class="nav-link" href="/businesses"><i class="fas fa-business-time"></i> Businesses</a>
      </li>
      <li class="nav-item">
        <i class="fas fa-search"></i><%= link_to "Search", business_search_path, class: 'nav-link search' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <div class="dropdown-item logout"><i class="fas fa-sign-out-alt"></i>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "logout"%>
            </div>
          <a class="dropdown-item" href="/users/<%= current_user.id %>/profile"><i class="fas fa-user-md"></i> User Profile</a>
            <div class="dropdown-item logout"><i class="fas fa-business-time"></i>
              <%= link_to "Register Business", new_business_path, class: "logout"%>
            </div>
            <% else %>
            <a class="dropdown-item" href="/users/sign_in"><i class="fas fa-sign-in-alt"></i> Login</a>
            <a class="dropdown-item" href="/users/sign_up"><i class="fas fa-user-plus"></i> Sign up</a>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeConnect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation_bar' %>
    <%= yield %>
  </body>
</html>